name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nodejs
      run: |
        sudo apt-get update 
        sudo apt-get -yq install curl gnupg
        curl -sL https://deb.nodesource.com/setup_14.x  | sudo bash
        sudo apt-get -yq install nodejs
    # install dependencies
    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run test:cov

  integration:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run integration tests
        run: npm run test:e2e

  image-build: 
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test run docker build
        run: docker build -t hagglex .

  deploy:
    needs: image-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploy to Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "scrapple-x"
          heroku_email: ${{secrets.DEPLOY_EMAIL}}
          usedocker: true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production